server:
  servlet:
    context-path: /plan
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plan
    username: postgres
    password: zephyr
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        # 时区, use 'timestamp without time zone' of postgresql
        jdbc.time_zone: UTC
        # 关键字转义
        globally_quoted_identifiers: true
        show_sql: true
        format_sql: true
  profiles:
    active: dev

flyway:
  locations: classpath:/db/migration

logging:
  level:
    root: info
    org.springframework.web: info
  path: /var/log/ushi/plan
