spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plan
    username: postgres
    password: zephyr
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
  profiles:
    active: dev

flyway:
  locations: classpath:/db/migration

logging:
  level:
    root: info
    org.springframework.web: info
  path: /var/log/ushi/plan
